# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./main.go"
  delay = 1000
  exclude_dir = ["node_modules", "tmp", "vendor"]
  include_ext = ["go", "toml", "html"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true

[color]
  main = "magenta"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true